### ISSUE TITLE
EOL check causes failure when pushing tags with comments

### ISSUE THREAD

**Issue by spoage** [pbaranchikov/stash-eol-check#1]
The following error occurs when I attempt to push tags (and a couple of objects) back into a repository with this hook enabled.

> # git push --tags ssh://our.stash.instance:7999/some/respository.git master
> remote: Hook com.pbaranchikov.stash.checks.EolCheckHook failed. Error:
> remote: '/usr/bin/git diff-tree --no-renames --always --format=commit %H%n%H%x02%P%x02%aN%x02%aE%x02%at%n%B%n%x03END%x04 --root --stdin --' exited with code 0 saying: error: Object 5bab3f10110c5d6d68a69ab4e347bf7d7d090f4e is a tag, not a commit or tree

**Comment by pbaranchikov** [comment]
Hello, SPoage.

I've seen the error once before, but unfortunately, I could not reproduce it any more. Could you please somehow clarify your steps. I've done the following:
- git commit
- git tag
- git commit
- git push --tags origin master

I have not got any errors.
Also, could you please specify versions of Git and Stash you are using.

**Comment by spoage** [comment]
> several merges that integrate a number of issues being released
> git commit -m 'commit message naming issue that tracks the release'
> git tag -a tag-name -m 'some message'
> git push --tags ssh://stash.some.domain:7999/some/repo.git master

And on the last command (the push) it throws the error in question.

Some details that might be of note:
1. All of this is done in an automated process, and the push uses an SSH key that DOES correspond to an actual Stash user, as opposed to a service user.
2. The push sends both commit refs/objects, as well as the tag refs, at the same time.

As for your questions, we're running the latest Stash version (3.5.1) and Git version 1.8.3.1

**Comment by pbaranchikov** [comment]
Thanks a lot. The failure only occurs when tag has a comment. This was the only condition I missed.

**Comment by pbaranchikov** [comment]
I've released version 0.3, which includes the fix. Could you please try it.

**Comment by spoage** [comment]
I've enabled the hook again, but it will be a day or two before we do another release, so it'll take that long to get a test case together. I'll let you know how it works out.

**Comment by spoage** [comment]
Looks good - thanks for the quick fix!
