### ISSUE TITLE
plugin configuration not available in repository settings -> workflow -> hooks

### ISSUE THREAD

**Issue by hitenc** [pbaranchikov/stash-eol-check#7]
Plugin configuration is  not available in repository settings -> workflow -> hooks although it is available under Pull Request -> Merge Checks

**Comment by pbaranchikov** [comment]
What is the version of plugin and version of Bitbucket Server?

**Comment by hitenc** [comment]
plugin version is 0.8 and bitbucket server version is 5.13.0

**Comment by hitenc** [comment]
Any update ?

**Comment by pbaranchikov** [comment]
I found the configuration to be broken since Bitbucket 5.2.0.
https://docs.atlassian.com/bitbucket-server/docs/5.9.0/reference/api-changelog.html
Unfortunately, they make on of their classes deprecated, so plugin does not fail in runtime, but is not working properly.

**Comment by pbaranchikov** [comment]
The issue is fixed in version 0.8.1.
