### ISSUE TITLE
stash-eol-check plugin

### ISSUE THREAD

**Issue by raj13aug** [pbaranchikov/stash-eol-check#9]
Are there any plans for the “stash-eol-checkr “app to be compatible with the Bitbucket server version 6.10 data center edition?

**Comment by pbaranchikov** [comment]
Hi. The plans exist. There is no technical problem. Plugin supports running in datacenter edition. The only problem here is to pass DataCenter certification in Atlassian.

**Comment by pbaranchikov** [comment]
Hi Datacenter edition is available now.
